server:
  port: 80

spring:
    application:
      name: cloud-order-service

eureka:
  client:
    #是否将自己注册进注册中心
    register-with-eureka: true
    fetch-registry: true
    service-url:
     # defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7002.com:7003/eureka/,http://eureka7001.com:7001/eureka/ #集群版
